- hosts: all
  gather_facts: True
  become: yes
  become_method: sudo

  tasks:
  - name: start database docker container
    command: /home/ubuntu/payworks/database/start_mongo.sh
    args:
        chdir: /home/ubuntu/payworks/database
  - name: build superheros docker container
    command: /home/ubuntu/payworks/superhero/build_image.sh
    args:
        chdir: /home/ubuntu/payworks/superhero
  - name: start superheros docker container
    command: /home/ubuntu/payworks/superhero/start_superheros.sh
    args:
        chdir: /home/ubuntu/payworks/superhero
